[[services]]
name = "postgres"
source = { type = "database" }

[[services]]
name = "nats"
source = { image = "nats:2.10" }
cmd = ["-js", "--http_port", "8222"]
healthcheckPath = "/"
healthcheckTimeout = 300

[[services]]
name = "api"
source = { path = "./api" }
healthcheckPath = "/health"
healthcheckTimeout = 300
depends_on = ["postgres", "nats"]

[services.api.environment]
DATABASE_URL = "${{postgres.DATABASE_URL}}"
NATS_URL = "nats://nats:4222"
API_PORT = "${{PORT}}"
JWT_SECRET = "${{JWT_SECRET}}"
LOG_LEVEL = "info"
RATE_LIMIT_RPS = "100"
MAX_BATCH_SIZE = "1000"